repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json|^.vscode/settings.json
      - id: pretty-format-json
        exclude: ^.devcontainer/devcontainer.json|^.vscode/settings.json
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/doublify/pre-commit-rust
    rev: "v1.0"
    hooks:
      - id: fmt
        args: [--all, --]
        env:
          PATH: "${HOME}/.cargo/bin:${PATH}"
      - id: clippy
        args: [--all-targets, --all-features, --, -D, warnings]
        env:
          PATH: "${HOME}/.cargo/bin:${PATH}"
      - id: cargo-check
        env:
          PATH: "${HOME}/.cargo/bin:${PATH}"
